# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DC_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.IntegerField(choices=[(0, b'superman'), (1, b'wonder_women'), (2, b'batman'), (3, b'green_lantern'), (4, b'flash'), (5, b'aquaman')])),
                ('player_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('answers_given', models.CharField(default=b'00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('qdone', models.IntegerField(default=40)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GOT_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('house', models.IntegerField(choices=[(0, b'house_arryen'), (1, b'house_baratheon'), (2, b'house_greyjoy '), (3, b'house_lanister'), (4, b'house_mormont'), (5, b' house_stark'), (6, b'house_targaryen '), (7, b'house_tyrell')])),
                ('status', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('answers_given', models.CharField(default=b'00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('qdone', models.IntegerField(default=40)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HP_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField(default=0)),
                ('house', models.IntegerField(choices=[(0, b'griffinder'), (1, b'hufflepuff'), (2, b'ravenclaw'), (3, b'slytherin')])),
                ('status', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('answers_given', models.CharField(default=b'00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('qdone', models.IntegerField(default=40)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MARVEL_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField(default=0)),
                ('house', models.IntegerField(choices=[(0, b'magneto'), (1, b'doom'), (2, b'kingpin'), (3, b'thanos'), (4, b'red_skull'), (5, b'venom')])),
                ('status', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('answers_given', models.CharField(default=b'00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('qdone', models.IntegerField(default=40)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.IntegerField()),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=10000)),
                ('solution', models.IntegerField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
            ],
        ),
    ]
