# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_player',
            name='qdone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='got_player',
            name='qdone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hp_player',
            name='qdone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marvel_player',
            name='qdone',
            field=models.IntegerField(default=0),
        ),
    ]
